### ISSUE TITLE
Problem with non blocking function

### ISSUE THREAD

**Issue by pakozm** [raksoras/luaw#3]
Hi, I'm trying to implement a non-blocking function for a computational intense process, but it is failing and being stuck with not apparent reason.
I have written a very basic handler which suffers the same problem:

```Lua
GET 'loop' {
  function(req, resp, pathParams)
    local scheduler = Luaw.scheduler
    local thread    = scheduler.startUserThread(function()
        for i=1,1000 do print(i) coroutine.yield() end
    end)
    return "Loop"
  end
}
```

The output of the HTTP GET in the terminal window is the following:

```
starting server on port 7001 ...
1
Error: ./bin/luaw_webapp.lua:355: ./bin/luaw_webapp.lua:187: No action found for path /favicon.ico for method GET
2
3 <--- FROZEN HERE
```

And it is frozen in the indicated line. The unique way to continue the loop is to do another HTTP GET over a different or the same path...

Am I misunderstanding something about threads in Luaw? I don't see the reason why the thread is stucked there :(

**Comment by raksoras** [comment]
General design philosophy  of Luaw is you should never have to yield/resume manually inside your code. Luaw does that for you automatically behind the scenes for any calls that block - read, write, connect etc. Take a look at connMT.read() and connMT.write() methods in lib/luaw_lib.lua to see how this is hooked up in Luaw's thread scheduler. If you thread makes read() on socket then Luaw will automatically swap it out when it blocks and resume it when the socket is ready with data to return. You almost never have to call coroutine:yield() directly.

Having said that cleanest way to achieve what you are trying to do is to use timer object. Something like this:
```lua
GET 'loop' {
  function(req, resp, pathParams)
    local scheduler = Luaw.scheduler
    local timer = Luaw.newTimer()
    local thread    = scheduler.startUserThread(function()
        for i=1,1000 do print(i) timer:sleep(1000) end   --in millis
    end)
    return "Loop"
  end
}
```

Luaw timer hooks up properly in luaw scheduler and it get's woken up every N milliseconds.

There is another way - closer to what you are trying - but it kinda exposes Luaw innards of Luaw and won't work as well. To go that way simply replace your coroutine.yield() with coroutine.yield(Luaw.TS_RUNNABLE). This signals Luaw scheduler that your user thread is runnable although it is yielding willingly. However, problem with this approach is this would make Luaw scheduler to add the user thread to it's run-queue but after that it will make uv_loop() call that will block till at least one event happens on any of the uv_watchers it is watching - something like socket being ready with data or client connecting on listen port etc. In absence of such event Luaw will stay blocked even though it has a runnable user thread in its queue. Once that event happens it will be unblocked and will process any ready threads from its run queue after it handles all event. You can verify this by making HTTP request to some other, unrelated handler on the same server and seeing that your original user thread proceeds by one iteration.

Using timer object avoids all this complication as the timer object is a valid event source which will unblock itself after the timeout. Of course, in real life you probably want read and write from your user thread to block/unblock your user thread.

Hope this helps.

**Comment by pakozm** [comment]
Many thanks for the explanation, it has been very insightful :-)
So, I will use the timer, with a low value for the milliseconds condition. I hope this would suffice for my particular case. And congratulations for the architecture and design of Luaw, it is really amazing and clean.
